name: very-good-coverage
description: 'Enforce LCOV Coverage Thresholds'
inputs:
  path:
    description: 'lcov path'
    required: false
    default: './coverage/lcov.info'
runs:
  using: 'node12'
  main: 'dist/index.js'
