name: ci
on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  e2e:
    defaults:
      run:
        working-directory: ./fixtures
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - uses: ./
        with:
          path: lcov.100.info
      - uses: ./
        with:
          path: lcov.95.info
          min_coverage: 90
      - uses: ./
        with:
          path: lcov.95.info
          exclude: '**/*_observer.dart'
      - uses: ./
        with:
          path: lcov.95.info
          exclude: '**/whatever.dart **/*_observer.dart **/does_not_matter.dart'
