name: "ci"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          path: "./fixtures/lcov.100.info"
